### ISSUE TITLE
elementClasses is not merged after re-render

### ISSUE THREAD

**Issue by mthadley** [metal/metal-component#4]
Given the following components:
```js
import Component from 'metal-jsx';

class Count extends Component {
	render() {
		const {count} = this.config;

		const classes = count === 0 ? "bar zero" : "bar";

		return <div class={classes}>{count}</div>;
	}
}

class Counter extends Component {
	render() {
		return (
			<div>
				<button data-onclick={() => {this.count += 1}}>Add</button>
				<Count count={this.count} elementClasses="foo" />
			</div>
		);
	}
}

Counter.STATE = {
	count: {
		value: 0
	}
}
```

When the `Count` component is initially rendered, it's `element` has the classes `"foo bar zero"`, but after the Add button is clicked, it only has `"bar"`. The `foo` class gets dropped after the re-render, however I would expect the `foo` class to always be present. I'm wondering, is this intended behavior?

As far as I know, `elementClasses` is not documented anywhere, but I'm assuming it is something component developers can make use of. I don't think I'm breaking anything by using an undocumented or private API.

A temporary work-around seems to involve explicitly referencing `elementClasses`:

```js
class Count extends Component {
	render() {
		const {count} = this.config;

		// Hacky, but you get the point...
		const classes = (count === 0 ? "bar zero " : "bar ") + this.elementClasses;

		return <div class={classes}>{count}</div>;
	}
}
```

Seems like this logic shouldn't be necessary, because why would we only want to merge elementClasses once?

Another thing I noticed, the docstring for `elementClasses` lists it's type as `Array<String>`, however it's validator checks if it's a `String`, so I'm guessing it is out of date.

**Comment by mairatma** [comment]
You were right, I've fixed this now, so just update your dependencies and this should work :)

**Comment by mairatma** [comment]
By the way, I've [fixed](https://github.com/metal/metal-component/commit/62db0ea9ce6cfa44c28bab93b797d7f97d37402f) the doc to state that `elementClasses` should be `string` instead of `Array<string>`, thanks for letting me know it was wrong!

**Comment by mthadley** [comment]
Awesome, thanks @mairatma!
